INCLUDE "data/map_songs.asm"
INCLUDE "data/map_header_pointers.asm"
INCLUDE "data/map_header_banks.asm"
INCLUDE "engine/pikachu_follow.asm"
INCLUDE "engine/pikachu_status.asm"
INCLUDE "engine/pikachu_emotions.asm"
INCLUDE "engine/pikachu_movement.asm"
INCLUDE "engine/pikachu_pic_animation.asm"

Func_fe66e:
	ret

OfficerJennySprite:    INCBIN "gfx/sprites/officer_jenny.2bpp"
PikachuSprite:         INCBIN "gfx/sprites/pikachu.2bpp"
SandshrewSprite:       INCBIN "gfx/sprites/sandshrew.2bpp"
OddishSprite:          INCBIN "gfx/sprites/oddish.2bpp"
BulbasaurSprite:       INCBIN "gfx/sprites/bulbasaur.2bpp"
JigglypuffSprite:      INCBIN "gfx/sprites/jigglypuff.2bpp"
Clefairy2Sprite:       INCBIN "gfx/sprites/clefairy2.2bpp"
ChanseySprite:         INCBIN "gfx/sprites/chansey.2bpp"
SurfingPikachuSprite:  INCBIN "gfx/sprites/surfing_pikachu.2bpp"
JessieSprite:          INCBIN "gfx/sprites/jessie.2bpp"
JamesSprite:           INCBIN "gfx/sprites/james.2bpp"
MimeySprite:           INCBIN "gfx/sprites/mimey.2bpp"
BeautySprite:          INCBIN "gfx/sprites/beauty.2bpp"
BCatcherGSprite:       INCBIN "gfx/sprites/bcatcher_girl.2bpp"
BlaineSprite:          INCBIN "gfx/sprites/blaine.2bpp"
ElectricianSprite:     INCBIN "gfx/sprites/electrician.2bpp"
FGuyPalletSprite:      INCBIN "gfx/sprites/fat_guy_palt.2bpp"
GirlPalletSprite:      INCBIN "gfx/sprites/palt_girl.2bpp"
OakLabFSprite:         INCBIN "gfx/sprites/oak_aidef.2bpp"
OakLabMSprite:         INCBIN "gfx/sprites/oakas.2bpp"