TrainerNames:
	db "Shorts Kid@"
	db "Bug Catcher♂@"
	db "Miniskirt@"
	db "Sailor@"
	db "Boy Scout@"
	db "Girl Scout@"
	db "Cosplayer♂@"
	db "Poké Nerd@"
	db "Mountaneir@"
	db "Biker♂@"
	db "Burglar@"
	db "Electrician@"
	db "Swimmer♂@"
	db "Fisherman@"
	db "Swimmer♀@"
	db "Roughneck@"
	db "Gambler@"
	db "Beauty@"
	db "Psychic♂@"
	db "Sound Tech@"
	db "Juggler@"
	db "Poké Tamer@"
	db "Bird Tamer♂@"
	db "Karate King@"
	db "RIVAL1@"
	db "PROF.OAK@"
	db "Bug Catcher♀@"
	db "Researcher♂@"
	db "Giovanni@"
	db "Rocket♂@"
	db "Elite Trainer♂@"
	db "Elite Trainer♀@"
	db "Bruno@"
	db "Brock@"
	db "Misty@"
	db "Lt.Surge@"
	db "Erika@"
	db "Koga@"
	db "Blaine@"
	db "Sabrina@"
	db "Gentleman@"
	db "RIVAL2@"
	db "RIVAL3@"
	db "Lorelei@"
	db "Priestess@"
	db "Agatha@"
	db "Lance@"
	db "Cosplayer♀@"
	db "Biker♀@"
	db "Psychic♀@"
	db "Bird Tamer♀@"
	db "Karate Queen@"
	db "Assistant@"
	db "Rocket♀@"
	db "Madame@"
	db "Priest@"
	db "Delinquent@"
	db "Dojo Master@"
	db "Fireman@"
	db "Firewoman@"
	db "Soldier@"
	db "Archer@"
