TrainerNames:
	db "Shorts Kid@"
	db "Bug Catcher♂@"
	db "Miniskirt@"
	db "Sailor"
	db "Boy Scout@"
	db "Girl Scout@"
	db "Cosplayer@"
	db "Poké Nerd@"
	db "Hiker@"
	db "Biker@"
	db "Burglar@"
	db "Electrician@"
	db "Swimmer♀@"
	db "Fisherman@"
	db "Swimmer♂@"
	db "Roughneck@"
	db "Gambler@"
	db "Adult Woman@"
	db "Psychicer@"
	db "Audio Tech@"
	db "Juggler@"
	db "Poké Tamer@"
	db "Bird Tamer@"
	db "BLACKBELT@"
	db "RIVAL1@"
	db "PROF.OAK@"
	db "Bug Catcher♀@"
	db "SCIENTIST@"
	db "GIOVANNI@"
	db "ROCKET@"
	db "COOLTRAINER♂@"
	db "COOLTRAINER♀@"
	db "BRUNO@"
	db "BROCK@"
	db "MISTY@"
	db "LT.SURGE@"
	db "ERIKA@"
	db "KOGA@"
	db "BLAINE@"
	db "SABRINA@"
	db "GENTLEMAN@"
	db "RIVAL2@"
	db "RIVAL3@"
	db "LORELEI@"
	db "CHANNELER@"
	db "AGATHA@"
	db "LANCE@"
